services:
  accounts:
    image: sandeep4396/accounts-svc:latest
    container_name: accounts-svc
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - financial-services
  loans:
    image: sandeep4396/loans-svc:latest
    container_name: loans-svc
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - financial-services
  cards:
    image: sandeep4396/cards_svc:latest
    container_name: cards-svc
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
        - financial-services
networks:
    financial-services:
        driver: bridge