server:
  port: 8080
spring:
  datasource:
    #H2 DB URL
    url: jdbc:h2:mem:testdb
    # Required for H2 database to specify the driver class. Driver class is necessary for Spring Boot to know how to connect to the H2 database.
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      # Enable H2 console for debugging
      enabled: true
  jpa:
    # Helpful for generating SQL queries specific to H2. This is necessary for Hibernate to understand how to interact with the H2 database.
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Automatically update the database schema based on the entity definitions. This is useful for development and testing, but should be used with caution in production environments.
      ddl-auto: update
      # Show SQL statements in the console for debugging purposes. This is helpful for developers to see the actual SQL queries being executed against the database, which can aid in troubleshooting and optimizing database interactions.
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    # Set the path for the Swagger UI. This allows developers to access the API documentation and test the endpoints through a web interface.
